1. Find total customers by countries?

Select
country,
count(customer_key) as total_customers
from gold.dim_customers
group by country
order by total_customers desc;

2.Find total customers by gender?

Select
gender,
count(customer_key) as total_customers
from gold.dim_customers
group by gender
order by total_customers desc;

3.Find total products by category?

Select
category,
count(product_key) as total_products
from gold.dim_products
group by category
order by total_products desc;

4.What is the avg costs in each category?

Select
category,
avg(round(cost,0)) as avg_costs
from gold.dim_products
group by category
order by avg_costs desc;

5.What is the total revenue generated for each category?

Select
p.category,
sum(f.sales_amount)total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.category
order by total_revenue desc;

6.Find total revenue is generated by each customer?

select
c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join  gold.dim_customers c
on c.customer_key = f.customer_key
group by
c.customer_key,
c.first_name,
c.last_name
order by total_revenue desc;

7.What is the distribution of sold items across countries?

select
c.country,
sum(f.quantity) as total_sold_items
from gold.fact_sales f 
left join gold.dim_customers c
on c.customer_key = f.customer_key
group by 
c.country
order by total_sold_items desc;
